#:schema node_modules/wrangler/config-schema.json

name = "dcabines"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "MY_KV"
id = "adbf928d4e2b48a58236b7fdd1870e43"

[[d1_databases]]
binding = "oltp"
database_name = "oltp"
database_id="52aa558c-6580-4cb9-a683-00aabc3d4ecd"
